Update dev_ios.yml

diff --git a/.github/workflows/dev_ios.yml b/.github/workflows/dev_ios.yml
--- a/.github/workflows/dev_ios.yml
+++ b/.github/workflows/dev_ios.yml
@@ -31,13 +31,21 @@ jobs:
       - run: flutter build ios --release --no-codesign
         if: startsWith(github.ref, 'refs/tags/ios-dev')
 
+      - name: List build output directory (Debug step)
+        run: ls -R build/ios/iphoneos  # List files in the output directory
+
       - name: Create IPA from build
         run: |
-          mkdir -p build/ios/ipa
-          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/
-          cd build/ios/ipa
-          zip -r FlutterApp.ipa Runner.app
-        working-directory: ./  # Make sure this is the root directory of your repo
+          if [ -d "build/ios/iphoneos/Runner.app" ]; then
+            mkdir -p build/ios/ipa
+            cp -R build/ios/iphoneos/Runner.app build/ios/ipa/
+            cd build/ios/ipa
+            zip -r FlutterApp.ipa Runner.app
+          else
+            echo "Runner.app not found. Please check the build process."
+            exit 1
+          fi
+        working-directory: ./  # Ensure this is the root directory of your repo
 
       - name: Upload iOS Dev IPA to GitHub Release
         if: startsWith(github.ref, 'refs/tags/ios-dev')
